# Generated by Django 5.2.6 on 2025-10-27 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACORouteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('best_distance', models.FloatField()),
                ('parameters', models.JSONField()),
                ('routes', models.JSONField()),
                ('success', models.BooleanField(default=True)),
            ],
        ),
    ]
