# Generated by Django 5.2.6 on 2025-10-27 05:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationExecution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('algorithm', models.CharField(choices=[('aco', 'Ant Colony Optimization'), ('dqn', 'Deep Q-Network')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En Ejecución'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('best_distance', models.FloatField(blank=True, null=True)),
                ('routes', models.JSONField(blank=True, null=True)),
                ('num_orders_processed', models.IntegerField(default=0)),
                ('num_vehicles_used', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='DQNState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_path', models.CharField(default='models/dqn_vrp_model.pth', max_length=255)),
                ('epsilon', models.FloatField(default=1.0)),
                ('total_episodes', models.IntegerField(default=0)),
                ('total_operations', models.IntegerField(default=0)),
                ('avg_reward', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_execution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dqn_state', to='optimization.optimizationexecution')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('add_order', 'Añadir Orden'), ('cancel_order', 'Cancelar Orden'), ('remove_vehicle', 'Remover Vehículo'), ('batch_add', 'Añadir Batch de Órdenes')], max_length=20)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('assigned', models.BooleanField(default=False)),
                ('reward', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='optimization.optimizationexecution')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['execution', 'operation_type'], name='optimizatio_executi_b24303_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('weight', models.FloatField()),
                ('status', models.CharField(max_length=10)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('delivery_lat', models.FloatField()),
                ('delivery_lng', models.FloatField()),
                ('customer_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='optimization.optimizationexecution')),
            ],
            options={
                'indexes': [models.Index(fields=['execution', 'order_id'], name='optimizatio_executi_ef64f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('vehicle_id', models.IntegerField()),
                ('stop_sequence', models.IntegerField()),
                ('stop_type', models.CharField(max_length=10)),
                ('distance_to_next', models.FloatField(blank=True, null=True)),
                ('cumulative_distance', models.FloatField(blank=True, null=True)),
                ('cumulative_load', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='optimization.optimizationexecution')),
            ],
            options={
                'ordering': ['vehicle_id', 'stop_sequence'],
                'indexes': [models.Index(fields=['execution', 'vehicle_id'], name='optimizatio_executi_ea60d2_idx'), models.Index(fields=['execution', 'order_id'], name='optimizatio_executi_bc177d_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField()),
                ('capacity', models.FloatField()),
                ('max_distance', models.FloatField(default=100.0)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='optimization.optimizationexecution')),
            ],
            options={
                'indexes': [models.Index(fields=['execution', 'vehicle_id'], name='optimizatio_executi_6fc8b5_idx')],
            },
        ),
    ]
