# Generated by Django 5.2.6 on 2025-10-29 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastACORoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('best_distance', models.FloatField()),
                ('parameters', models.JSONField()),
                ('routes', models.JSONField()),
                ('num_orders_processed', models.IntegerField()),
                ('num_vehicles_used', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Last ACO Route',
                'verbose_name_plural': 'Last ACO Routes',
                'ordering': ['-executed_at'],
            },
        ),
    ]
