# Generated by Django 5.2.6 on 2025-10-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0002_optimizationexecution_dqnstate_operationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesnapshot',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclesnapshot',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='operation_type',
            field=models.CharField(choices=[('add_order', 'Añadir Orden'), ('cancel_order', 'Cancelar Orden'), ('remove_vehicle', 'Remover Vehículo'), ('batch_add', 'Añadir Batch de Órdenes'), ('status_change', 'Cambio de Estado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordersnapshot',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
